### ISSUE TITLE
Issues with Firefox and Thunderbird under Fedora 40

### ISSUE THREAD

**Issue by dev4inno** [Cairo-Dock/cairo-dock-core#28] opened 2024-08-17 10:56 UTC
Hello,

first of all: I am on Fedora 40 with Mate Desktop and Compiz.
Everything runs perfect - except two applications: Thunderbird and Firefox.
Not sure if that's related to the new names introduced in Fedora 39/40:

- org.mozilla.firefox (instead of firefox)
- org.mozilla.thunderbird (instead of thunderbird).

Before upgrading to Fedora 40 I was on Fedora 38 and had no issues with these applications in Cairo-Dock.

It seems to be similar to issue #25 (Icons duplicate when running some applications). I tried the solution, but it does not work.
Could it be that the starter name is truncated in the cairo-dock version delivered with Fedora (3.5.0)?

When I run Firefox and Thunderbird I get this behavior (both active Firefox and Thunderbird sessions are shown under Thunderbird):

![cairo-dock_starter_issues](https://github.com/user-attachments/assets/022f04f5-c741-40b1-93ec-84652085aa3c)

And if I add Firefox to Cairo-Dock before Thunderbird it would be the other way round (both active Firefox and Thunderbird sessions are shown under Firefox) ...

Not sure if this occurs in other distributions as well.

If something related to this bug has been changed in the source code I can give it a try and compile the latest version under Fedora 40.
In this case I need to know how to build it under Fedora.

**Comment by dkondor** [comment] 2024-08-18 16:44
Hi,

yes, app-ids are truncated in 3.5 and also already in 3.4, due to other issues with apps, but this obviously does not work with the newer, reverse DNS style IDs that are being used by more apps.

In the current beta (version 3.5.99 in the master branch here), I have changed this behavior, so if you're able to compile from source, it should work (however, it could introduce other regressions). Any feedback on this version is very welcome :). The "old" instructions on compiling should still work: https://glx-dock.org/ww_page.php?p=By%20compiling&lang=en
(there is some additional info [here](https://github.com/Cairo-Dock/cairo-dock-core/blob/master/README_Wayland.md) about Wayland-related stuff, but since you're trying to run CD on X11, it is not very relevant for your case).

**Comment by dev4inno** [comment] 2024-08-19 10:48
Thank you for your fast reply :-)

Fedora 40 Mate is already based on Wayland.
In addition to the instructions for Fedora I had to install these packages:

sudo dnf install librsvg2-devel
sudo dnf install gtk-layer-shell-devel

But unfortunately I got stuck here:


`/home/haegar/Downloads/cairo-dock/cairo-dock-core/src/implementations/cairo-dock-wayland-manager.c: In function 'init':
/home/haegar/Downloads/cairo-dock/cairo-dock-core/src/implementations/cairo-dock-wayland-manager.c:587:13: error: implicit declaration of function 'gldi_wayland_hotspots_try_init' [-Wimplicit-function-declaration]
  587 |         if (gldi_wayland_hotspots_try_init (registry))
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/haegar/Downloads/cairo-dock/cairo-dock-core/src/implementations/cairo-dock-wayland-manager.c:588:50: error: 'gldi_wayland_hotspots_update' undeclared (first use in this function)
  588 |                 cmb.update_polling_screen_edge = gldi_wayland_hotspots_update;
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

By the way, when is the release of the new version (I guess it will be 3.6) planned?

**Comment by dev4inno** [comment] 2024-08-19 19:50
Good news:

I saw that the Fedora package maintainer has provided rpm packages for version 3.5.99.
However, these packages are for the unreleased Fedora 41 and not for the current Fedora 40.
First I tried the last version from 2024-08-16, but it had some dependencies that could not be met in Fedora 40.
Then I took this versions and was able to install the packages:

- cairo-dock-3.5.99^20240501git1f31686-1.fc41  https://koji.fedoraproject.org/koji/buildinfo?buildID=2448189
- cairo-dock-plug-ins-3.5.99^20240501git9901f7d-1.fc41 https://koji.fedoraproject.org/koji/buildinfo?buildID=2448190

Firefox and Thunderbird are now handled correctly (and separately) in cairo-dock :-)

Thank you for fixing the bug!

So we must wait for the official release 3.6 ...

**Comment by dkondor** [comment] 2024-08-19 20:16
Hi,
thank you for reporting back and it is good to know that this issue is fixed in the beta :)
Also thank you for reporting the details of the build issue, I'll look into that separately.
There is no release date / plan for 3.6 yet -- first I need to update the documentation with the changes, then get people to test it more widely and fix bugs that come up :)

**Comment by dkondor** [comment] 2024-09-21 19:17
I've released a new stable version (3.5.1) which includes the fixes, so closing this issue.

**Closed by dkondor** 2024-09-21 19:17 UTC
